spring:
  application:
    name: xcube-zipkin-server
  profiles: 
    active: native
server:
  port: 8769
# 关闭验证
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8500/eureka/
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 47.92.246.2:9200
